#pragma once

enum class ClientState {
  UNAUTHORIZED,
  AUTHORIZED
  //... idk
};

enum class PageTypes {
  MAIN_LOGIN_PAGE,
  TWO_FACTOR_LOGIN_PAGE,
  QR_LOGIN_PAGE,
  CLOUD_PASSWORD_PAGE
};

enum class AuthorizationState {
  READY,
  LOGGING_OUT,
  CLOSING,
  CLOSED,
  WAIT_PHONE_NUMBER,
  WAIT_PREMIUM_PURCHASE,
  WAIT_EMAIL_ADDRESS,
  WAIT_EMAIL_CODE,
  WAIT_CODE,
  WAIT_REGISTRATION,
  WAIT_PASSWORD,
  WAIT_OTHER_DEVICE_CONFIRMATION,
  WAIT_TDLIB_PARAMETERS
};